jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      highlight_sql: true
data:
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}

springdoc:
  swagger-ui:
    operations-sorter: method

logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace

      springframework:
        security: debug
        jdbc:
          core:
            JdbcTemplate: debug

server:
  port: 8080
